version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: 
  - Debug
  - Release
clone_depth: 1
shallow_clone: true 
before_build:
  - dotnet restore
build_script:
  - ps: |
      if ( $env:APPVEYOR_REPO_TAG ) {
          dotnet build /p:Version=$env::APPVEYOR_REPO_TAG
      } else {
          dotnet build
      }
  
test_script:
  - dotnet test Personnummer.Tests

# Only publish if on master branch and not a PR.
after_test:
  - ps: |
      if ( $env:APPVEYOR_REPO_BRANCH -eq "master" -and $env:APPVEYOR_PULL_REQUEST_NUMBER ) {
          dotnet publish "Personnummer\Personnummer.csproj" -c Release -o artifacts\    
      }

for:
  - branches:
      only:
        - master
    configuration: Release
    after_test:
      - dotnet publish "Personnummer\Personnummer.csproj" -c Release -o artifacts\                
    artifacts:
      - path: artifacts\*.*
      
    #deploy:
    #  - provider: GitHub
    #    artifact: artifacts\/.*\.nupkg/
    #    draft: false
    #    prerelease: false
    #    on:
    #      APPVEYOR_REPO_TAG: true
