version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: 
- Debug
- Release
clone_depth: 1
before_build:
- dotnet restore
build_script:
- dotnet build
test_script:
- dotnet test Personnummer.Tests

for:
- branches:
    only:
     - master
  configuration: Release
  after_test:
  - dotnet publish "Personnummer\Personnummer.csproj" -c %CONFIGURATION% -o artifacts\%CONFIGURATION%                
  artifacts:
  - path: artifacts\**\*.*