version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
clone_depth: 1
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  project: Personnummer.sln
  publish_nuget: true
  verbosity: minimal
