name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set up dotnet.
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Build
        run: dotnet build --configuration Release Personnummer
      - name: Package
        run: dotnet pack --configuration Release Personnummer
      - name: publish Nuget
        run: dotnet nuget push Personnummer/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
      - name: publish GH
        run: dotnet nuget push Personnummer/bin/Release/*.nupkg -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/Personnummer/index.json